ALTER SEQUENCE mtr_ids RESTART WITH 1;
DELETE FROM mtr;
INSERT INTO mtr (geom) SELECT geom FROM mtr_01;
INSERT INTO mtr (geom) SELECT geom FROM mtr_02;
INSERT INTO mtr (geom) SELECT geom FROM mtr_03;
INSERT INTO mtr (geom) SELECT geom FROM mtr_04;
INSERT INTO mtr (geom) SELECT geom FROM mtr_07;
INSERT INTO mtr (geom) SELECT geom FROM mtr_08;
INSERT INTO mtr (geom) SELECT geom FROM mtr_09;
INSERT INTO mtr (geom) SELECT geom FROM mtr_10;
INSERT INTO mtr (geom) SELECT geom FROM mtr_11;
INSERT INTO mtr (geom) SELECT geom FROM mtr_13;
INSERT INTO mtr (geom) SELECT geom FROM mtr_14;
INSERT INTO mtr (geom) SELECT geom FROM mtr_17;
INSERT INTO mtr (geom) SELECT geom FROM mtr_18;
INSERT INTO mtr (geom) SELECT geom FROM mtr_23;
INSERT INTO mtr (geom) SELECT geom FROM mtr_24;
INSERT INTO mtr (geom) SELECT geom FROM mtr_25;
INSERT INTO mtr (geom) SELECT geom FROM mtr_31;
INSERT INTO mtr (geom) SELECT geom FROM mtr_32;
INSERT INTO mtr (geom) SELECT geom FROM mtr_33;
INSERT INTO mtr (geom) SELECT geom FROM mtr_37;
INSERT INTO mtr (geom) SELECT geom FROM mtr_38;
INSERT INTO mtr (geom) SELECT geom FROM mtr_42;
INSERT INTO mtr (geom) SELECT geom FROM mtr_43;
INSERT INTO mtr (geom) SELECT geom FROM mtr_44;
SELECT * FROM mtr;