ALTER SEQUENCE rz20_ids RESTART WITH 1;
DELETE FROM rz20;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_01;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_02;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_03;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_04;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_05;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_06;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_07;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_08;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_09;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_10;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_11;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_12;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_13;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_14;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz004;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_16;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_17;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_18;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_19;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_20;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_23;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_25;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_27;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_29;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_34;
INSERT INTO rz20 (geom,number_rz) SELECT geom,number_rz FROM rz20_36;
SELECT * FROM rz20;