ALTER SEQUENCE rz35_ids RESTART WITH 1;
DELETE FROM rz35;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_09;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_11;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_12;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_13;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_14;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_15;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_16;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_17;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_18;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_19;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_20;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_23;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_25;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_26;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_27;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_29;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_32;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_33;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_37;
INSERT INTO rz35 (geom,number_rz) SELECT geom,number_rz FROM rz35_42;
SELECT COUNT(id) FROM rz35;