ALTER SEQUENCE rzv_buf_ids RESTART WITH 1;
DELETE FROM rzv_buf;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_07;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_09;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_11;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_14;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_15;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_16;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_17;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_18;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_20;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_23;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_24;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_25;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_26;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_29;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_31;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_32;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_33;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_35;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_36;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_37;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_38;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_40;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_42;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_44;
INSERT INTO rzv_buf  (geom) SELECT geom FROM rzv_buf_45;
SELECT COUNT(id) FROM rzv_buf;